### ISSUE TITLE
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x447f9e2]

### ISSUE THREAD

**Issue by ghost** [PeterCxy/gozbar#4]
Hello @PeterCxy, 

I have been working on a real-time QR-Code and barcode scanner using golang, gocv and gozbar. I am analysing each frame to detect the object I would like to scan. After converting the image frame from Mat() to image.Image I am doing the following: 

```
scanner := zbar.NewScanner()
scanner.SetConfig(0, zbar.CFG_ENABLE, 1)
scanner.Scan(img)
defer scanner.Destroy()
	img.First().Each(func(str string) {
		fmt.Println(str)
		if str!= " " {
			fmt.Println(str)
		}

	})
```
 I have a segmentation violation code.
After debugging I can see `img.First().Each(func(str string){}` is causing the following error: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x447f9e2]

goroutine 1 [running]:
github.com/PeterCxy/gozbar.(*Symbol).Data.func1(0x0, 0x0)
```

Do you have any suggestion?

**Comment by PeterCxy** [comment]
This project was created years ago and has long been unmaintained. I am not even personally using Go anymore. The project is pretty much unsupported and probably will not work at this point.

**Comment by ghost** [comment]
ok, thank you :)
